### ISSUE TITLE
No module named 'nudenet'

### ISSUE THREAD

**Issue by GDani31** [bedapudi6788/NudeNet#116]
```
C:\Users\danid>pip show nudenet
Name: nudenet
Version: 3.0.1
Summary: Lightweight Nudity Detection
Home-page: https://github.com/notAI-tech/nudenet
Author: BEDAPUDI PRANEETH
Author-email: praneeth@bpraneeth.com
License: MIT
Location: d:\miniconda3\lib\site-packages
Requires: numpy, onnxruntime, opencv-python
Required-by:

C:\Users\danid>python
Python 3.10.12 (main, Jun 14 2023, 19:14:29)  [GCC 13.1.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import nudenet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'nudenet'
```
what am i doing wrong?
I did
```
pip install --upgrade nudenet

**Comment by bedapudi6788** [comment]
Hi, that seems weird. Can you try to replicate this on google colab and share the link here.

**Comment by GDani31** [comment]
> Hi, that seems weird. Can you try to replicate this on google colab and share the link here.

For some reason it works there
```
!pip install --upgrade nudenet
!python
>> import nudenet
```
Is this a windows problem?

There is no error in colab, it does import as normal, no errors.

**Comment by bedapudi6788** [comment]
may be some environment related issue. make sure your pip and python are from same environment. `which pip` and `which python` something like that. or may be use `python -m pip install` to install nudenet and try once

**Comment by GDani31** [comment]
yes, i am an idiot, it did not found the package because of miniconda3. its now fixed.
