### ISSUE TITLE
Is NudeNet v3 train by yolov8 ? 

### ISSUE THREAD

**Issue by zhouyang986** [bedapudi6788/NudeNet#119]
is NudeNet v3 train by yolov8 ? 
so nice and thank you !

**Comment by bedapudi6788** [comment]
Yes, yolov8n

**Comment by skier233** [comment]
Yolov8 has a GNU license. By posting your source here using yolov8, you are required to use the same license:
https://github.com/ultralytics/ultralytics/blob/main/LICENSE

**Comment by bedapudi6788** [comment]
changed
