### ISSUE TITLE
Model performance

### ISSUE THREAD

**Issue by lxknvlk** [bedapudi6788/NudeNet#12]
So the demo page does classification in 1-1.2 seconds. How can the model be sped up?

**Comment by bedapudi6788** [comment]
The demo is hosted on a machine with 2 shared vcpus. Just use some machine with GPU for beter performance (should give you atleast 10x-20x speedup easily). If you really need ultra fast performance, you can to quantization. But, that will affect the accuracy.

**Comment by lxknvlk** [comment]
@bedapudi6788 are there any additional configurations needed for it to work on GPU?

**Comment by bedapudi6788** [comment]
You just need to use tf gpu.

**Comment by lxknvlk** [comment]
I have just ran the model on AWS gpu instance, tesla v60 and it was horribly slow. 

Next lines gave me outputs:

        print("GPU Available: ", tf.test.is_gpu_available())
        print("Built with cuda: ", tf.test.is_built_with_cuda())
        sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))

        GPU Available:  False
        Built with cuda:  True
        Device mapping:
        /job:localhost/replica:0/task:0/device:XLA_GPU:0 -> device: XLA_GPU device
        /job:localhost/replica:0/task:0/device:XLA_CPU:0 -> device: XLA_CPU device

**Comment by bedapudi6788** [comment]
```
    GPU Available:  False
```
in your output, it clearly says that tensorflow isn't using gpu. Get tensorflow to use gpu and it will work as expected.

**Comment by lxknvlk** [comment]
@bedapudi6788 you were correct! I have correctly configured the gpu and environment, not getting `GPU Available: True`, and getting an average of 350ms for the object detector check on an AWS g3s.xlarge instance with the Tesla M60.
