### ISSUE TITLE
pretrained model best.onnx

### ISSUE THREAD

**Issue by waquey** [bedapudi6788/NudeNet#124]
Dear great author, 
Thanks for the great work. I've tried to view the "best.onnx" and find it is converted from pytorch 2.0.1 with onnx v8. 
Could you please provide the original pytorch model graph as well? 

Currently I've tried to use pytorch (torch.nn.Conv2d(128, 64, kernel_size=(1, 1), stride=(1, 1)  )) to build graph, which is /model.4/cv2/conv/Conv_output_0 [kernel_shape = stride = 1 and pads=0,0,0,0] in onnx

However, the results vary a lot for pytorch and onnx even if the weights/bias is the same 

Thanks

**Comment by bedapudi6788** [comment]
@waquey https://github.com/notAI-tech/NudeNet/blob/v3/best.pt is the pytorch model.
