### ISSUE TITLE
Accuracy Issues with Certain Classes in NudeClassifier

### ISSUE THREAD

**Issue by wdcs-divyeshpatel** [bedapudi6788/NudeNet#126]
Hello,

I've been using the NudeClassifier for moderation purposes and have noticed that the accuracy is lower for certain classes. I have ensured that the model is properly trained and the input data is of good quality.

I believe this is crucial for many users who rely on this tool for content moderation. If possible, could you look into this or provide guidance on any potential improvements or workarounds? If needed, I can provide sample images (with sensitive content blurred or removed) to help in the troubleshooting process.

Thank you for your hard work on this project, and I look forward to any assistance or updates on this matter.

**Comment by bedapudi6788** [comment]
Hi, NudeClassifier is currently unsupported. v3 has only detector I am working on making a more detailed classifier. Will take time though.
