### ISSUE TITLE
'classifier_checkpoint_path'

### ISSUE THREAD

**Issue by lxknvlk** [bedapudi6788/NudeNet#13]
It is unclear, what do i have to put in 'classifier_checkpoint_path' and 'detector_checkpoint_path'?

I have found this code in your repo
>m = Detector('/Users/bedapudi/Desktop/inference_resnet50_csv_14.h5')

Can you share the inference_resnet50_csv_14.h5 file?

Are those the models from https://github.com/lxknvlk/NudeNet-models that i have to use in those paths?

**Comment by bedapudi6788** [comment]
Just download the classifier_checkpoint from NueNet-models repo and pass it's path here.
