### ISSUE TITLE
I made a censor extension for stable diffusion web ui using nudenet

### ISSUE THREAD

**Issue by w-e-w** [bedapudi6788/NudeNet#131]
just want to let you know that I made a censor extension for [stable diffusion web ui](https://github.com/AUTOMATIC1111/stable-diffusion-webui) using nudenet
and I like to say it works pretty nicely
here's the repo url https://github.com/w-e-w/sd-webui-nudenet-nsfw-censor if you're interested

some key differences of my implementation

- I implement my own censoring function, (I started working on this before you committed your censor)
- as opposed to just painting the regions black I've provided different filter functions including blurring pixelation and filling with color like yours
- and I also go for a elliptical shape (by default) for the mask area as opposed to square
- I make threshold for each class individually configurable
- to compensate the nudenet's accuracy by expanding the detected boxs by different amounts for each class
- I did not use your pip package instead I copy the model directly to my repo

**Comment by w-e-w** [comment]
@poisenbery I'm fully aware that this is not a social media for self promotion

this post was merely to let the author that I have made something off his project
similar to this post [Onnx Post-Processing, NMS, TensoRT](https://github.com/notAI-tech/NudeNet/issues/127)

I explained in post what I did different in my censoring filter

I believe my implantation has improved on his bare bones implementation of censoring
which is just draw a black box on detected regions
the issue with nudenet is that it's accuracy is not good enough to be used directly in that fashion

if the author wishes he can potentially reuse some of my code

**Comment by bedapudi6788** [comment]
@w-e-w I am happy you shared. I will add the project in README. nice work!

**Comment by w-e-w** [comment]
@bedapudi6788 thank you
it's an honor that you added it to readme
