### ISSUE TITLE
New detector only inputs path, can't use with cv images.

### ISSUE THREAD

**Issue by rbtreee** [bedapudi6788/NudeNet#143]
I noticed that the new detector can't handle any other input other than image paths. I think it would be beneficial be be able to use it with an already loaded image. This issue happens due to the function **_read_image**. By just changing 2 lines of code you would be able to use ndarray's as input.

```
def _read_image(image_path, target_size=320):
    if(type(image_path) == str):
        img = cv2.imread(image_path)
    else:
        #assuming that image_path is an np.ndarray
        img = image_path

```

**Comment by bedapudi6788** [comment]
@rbtreee  Can you submit a MR? thanks

**Comment by enkeejunior1** [comment]
I opened PR for this issue. 
https://github.com/notAI-tech/NudeNet/pull/144

**Comment by bedapudi6788** [comment]
merged, thanks. will push the new version
