### ISSUE TITLE
tensor is not an element of this graph, running with pm2

### ISSUE THREAD

**Issue by lxknvlk** [bedapudi6788/NudeNet#15]
Running the scrip normally works. 

But when i try to run my python server that uses nudenet via pm2, i get this error:

		0|server 1  | Exception happened during processing of request from ('127.0.0.1', 46026)
		0|server 1  | Traceback (most recent call last):
		0|server 1  |   File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
		0|server 1  |     self.finish_request(request, client_address)
		0|server 1  |   File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
		0|server 1  |     self.RequestHandlerClass(request, client_address, self)
		0|server 1  |   File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
		0|server 1  |     self.handle()
		0|server 1  |   File "/usr/lib/python3.6/http/server.py", line 418, in handle
		0|server 1  |     self.handle_one_request()
		0|server 1  |   File "/usr/lib/python3.6/http/server.py", line 406, in handle_one_request
		0|server 1  |     method()
		0|server 1  |   File "/home/ubuntu/nnserver.py", line 76, in do_POST
		0|server 1  |     handleRequest(self)
		0|server 1  |   File "/home/ubuntu/nnserver.py", line 61, in handleRequest
		0|server 1  |     result = detector.detect('/home/ubuntu/image/image_small.jpg')
		0|server 1  |   File "/usr/local/lib/python3.6/dist-packages/nudenet/detector.py", line 31, in detect
		0|server 1  |     boxes, scores, labels = Detector.detection_model.predict_on_batch(np.expand_dims(image, axis=0))
		0|server 1  |   File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1273, in predict_on_batch
		0|server 1  |     self._make_predict_function()
		0|server 1  |   File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 554, in _make_predict_function
		0|server 1  |     **kwargs)
		0|server 1  |   File "/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py", line 2744, in function
		0|server 1  |     return Function(inputs, outputs, updates=updates, **kwargs)
		0|server 1  |   File "/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py", line 2546, in __init__
		0|server 1  |     with tf.control_dependencies(self.outputs):
		0|server 1  |   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 5426, in control_dependencies
		0|server 1  |     return get_default_graph().control_dependencies(control_inputs)
		0|server 1  |   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 4867, in control_dependencies
		0|server 1  |     c = self.as_graph_element(c)
		0|server 1  |   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3796, in as_graph_element
		0|server 1  |     return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
		0|server 1  |   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3875, in _as_graph_element_locked
		0|server 1  |     raise ValueError("Tensor %s is not an element of this graph." % obj)
		0|server 1  | ValueError: Tensor Tensor("filtered_detections/map/TensorArrayStack/TensorArrayGatherV3:0", shape=(?, 300, 4), dtype=float32) is not an element of this graph.

The pm2 python interpreter seems to be "CPython".

**Comment by bedapudi6788** [comment]
@lxknvlk although I have no experience with pm2, this looks like very similar to https://stackoverflow.com/questions/51127344/tensor-is-not-an-element-of-this-graph-deploying-keras-model 

Try adding 
```
import tensorflow as tf
graph = tf.get_default_graph()
with graph.as_default():
       <prediction code>
``` 
in the python part. This should work.

**Comment by bedapudi6788** [comment]
@lxknvlk were able to get this working?

**Comment by lxknvlk** [comment]
@bedapudi6788 
I use the detector like this 

        from nudenet import NudeDetector
        detector = NudeDetector('/home/ubuntu/NudeNet/detector_model')
        result = detector.detect('/home/ubuntu/image/image_small.jpg')

Do i need to download the source code, then make changes there, compile and try then?

**Comment by lxknvlk** [comment]
@bedapudi6788 

I have tried with next code, still same error

        import tensorflow as tf

        class Detector():
            detection_model = None
            classes = [
                'BELLY',
                'BUTTOCKS',
                'F_BREAST',
                'F_GENITALIA',
                'M_GENETALIA',
                'M_BREAST',
            ]

            def __init__(self, model_path):
                graph = tf.get_default_graph()
                with graph.as_default():
                    Detector.detection_model = models.load_model(model_path, backbone_name='resnet101')

            def detect(self, img_path, min_prob=0.6):
                graph = tf.get_default_graph()
                with graph.as_default():
                    image = read_image_bgr(img_path)
                    image = preprocess_image(image)
                    image, scale = resize_image(image)
                    boxes, scores, labels = Detector.detection_model.predict_on_batch(np.expand_dims(image, axis=0))
                    boxes /= scale
                    processed_boxes = []
                    for box, score, label in zip(boxes[0], scores[0], labels[0]):
                        if score < min_prob:
                            continue
                        box = box.astype(int).tolist()
                        label = Detector.classes[label]
                        processed_boxes.append({'box': box, 'score': score, 'label': label})

                return processed_boxes

**Comment by lxknvlk** [comment]
@bedapudi6788 i have fixed it like this:

        class Detector():
            detection_model = None
            session = None
            graph = None
            classes = [
                'BELLY',
                'BUTTOCKS',
                'F_BREAST',
                'F_GENITALIA',
                'M_GENETALIA',
                'M_BREAST',
            ]

            def __init__(self, model_path):
                self.session = tf.Session()
                self.graph = tf.get_default_graph()
                
                with self.graph.as_default():
                    with self.session.as_default():
                        self.detection_model = models.load_model(model_path, backbone_name='resnet101')

            def detect(self, img_path, min_prob=0.6):
                with self.graph.as_default():
                    with self.session.as_default():
                        image = read_image_bgr(img_path)
                        image = preprocess_image(image)
                        image, scale = resize_image(image)
                        boxes, scores, labels = self.detection_model.predict_on_batch(np.expand_dims(image, axis=0))
                        boxes /= scale
                        processed_boxes = []
                        for box, score, label in zip(boxes[0], scores[0], labels[0]):
                            if score < min_prob:
                                continue
                            box = box.astype(int).tolist()
                            label = Detector.classes[label]
                            processed_boxes.append({'box': box, 'score': score, 'label': label})

                return processed_boxes
