### ISSUE TITLE
the box is wrong point

### ISSUE THREAD

**Issue by try2020-code** [bedapudi6788/NudeNet#151]
![image](https://github.com/notAI-tech/NudeNet/assets/84961646/c5f97b9d-64ec-4661-8c94-855672d091a7)

**Comment by bedapudi6788** [comment]
@try2020-code oh, weird, can you share the image with me? some padding post-processing issues may be.

**Comment by try2020-code** [comment]
> @try2020-code oh, weird, can you share the image with me? some padding post-processing issues may be.
Pornographic images can't be put here, but I think any pornographic image would produce the same result

**Comment by try2020-code** [comment]
> @try2020-code oh, weird, can you share the image with me? some padding post-processing issues may be.

pip install nudenet==3.0.8 will be ok

**Comment by bedapudi6788** [comment]
@try2020-code https://colab.research.google.com/drive/1WChIMZ9Yzseije3Oj-Ye-cGCMLw8azvZ?usp=sharing

here it is working fine.

you can email me the photo or send a link here

**Comment by try2020-code** [comment]
> @try2020-code https://colab.research.google.com/drive/1WChIMZ9Yzseije3Oj-Ye-cGCMLw8azvZ?usp=sharing
> 
> here it is working fine.
> 
> you can email me the photo or send a link here

 
<img width="960" alt="sex_copy" src="https://github.com/notAI-tech/NudeNet/assets/84961646/6faa75f5-6252-444a-b3ed-1fc637a22110">

`from nudenet import NudeDetector
#nude_detector = NudeDetector(model_path="C:\\Users\\1\\AppData\\Roaming\\Python\\Python311\\site-packages\\nudenet\\640m.onnx",inference_resolution=640)
nude_detector = NudeDetector()
res = nude_detector.detect('C:\\Users\\1\\Desktop\\temp\\sex.png') # Returns list of detectionsvar
res2= nude_detector.censor('C:\\Users\\1\\Desktop\\temp\\sex.png')
print(res)`

**Comment by try2020-code** [comment]
I remember when I first tried the 640m model. It's never been normal

**Comment by bedapudi6788** [comment]
On this image, it is drawing in-correctly. I think I understand the issue, will push an update

**Comment by bedapudi6788** [comment]
@try2020-code this is now fixed in the version 3.4.2

![aa_censored](https://github.com/notAI-tech/NudeNet/assets/15898654/94fcb28a-be8f-4753-84ac-9f7af8d735b8)
