### ISSUE TITLE
nudenet_classifier_url

### ISSUE THREAD

**Issue by mecmec05** [bedapudi6788/NudeNet#16]
I ran your script on a Debian VPS 9 doing all the following steps:

1. Update Python to 3.5
2. git clone https://github.com/bedapudi6788/NudeNet.git
3. I made sure to run the docker system with port 8500.
4. I put the following code in a test.py file:

```
#!/usr/bin/env python3.5
import nudeclient
# Single image prediction
print (nudeclient.predict ( '/home/test/NudeNet/img_5d586cf31de18.jpg'))
```

As soon as I run it works well
But I was wondering if it was possible to get "nudenet_classifier_url" in order to do like you on your demo to scan directly via URLs with return json.

cordially

**Comment by bedapudi6788** [comment]
For my demo, I use http://github.com/bedapudi6788/pydload this repo to download the image from url and run prediction on it.

**Comment by mecmec05** [comment]
I just tested, it's great!
But I have difficulties to create a python file so that it also web server that also manages pydload and also the docker.

Is it possible to have an example?

I almost never touch Python, bad knowledge in python. I am rather oriented nginx, php, javascript .. but not python!

**Comment by bedapudi6788** [comment]
@mecmec05 Here you go
```
import pydload
import uuid
import json
import time
import requests

from flask import Flask, request
from flask_cors import CORS, cross_origin

import nudeclient

app = Flask(__name__)
cors = CORS(app)

@app.route('/hello')
@cross_origin()
def hello():
    return "Hello World!"

@app.route('/nudenet_classifier_url', methods=['GET', 'POST'])
def nudenet_classifier_from_url():
    if request.method == 'GET':
        url = request.args.get('url')
    elif request.method == 'POST':
        url = request.json['url']

    try:
        path = str(uuid.uuid4())
        dload_status = pydload.dload(url, path, timeout=2 ,max_time=3)

        if not dload_status:
            return json.dumps({'error': 'File too large to download'})

        res = nudeclient.predict(path)[path]
        
        for key, value in res.items():
            res[key] = str(value)

        return json.dumps(res)
    except Exception as ex:
        return json.dumps({'error': str(ex)})


if __name__ == '__main__':
    app.run(debug=False, threaded=True, port=6788, host='0.0.0.0')
```

This example flask app downloads the photo from the url provided and runs prediction with nudeclient and returns the response in a json format.

GET Request example: http://localhost:6788/nudenet_classifier_url?url=http://bpraneeth.com/images/profile_pic.png

POST request can also be done in similar format.
