### ISSUE TITLE
file signature not found

### ISSUE THREAD

**Issue by ASentimentalMan** [bedapudi6788/NudeNet#18]
## Describe the bug and error messages
Error 'file signature not found' occurs when trying to load model to Classifier & Detector

## The code snippet which gave this error
> Classifier Usage

classifier = NudeClassifier('./NudeNet-models/v1/classifier_model')

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-10-a9d05d842fe9> in <module>()
----> 1 classifier = NudeClassifier('./NudeNet-models/v1/classifier_model')

4 frames
/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
    140         if swmr and swmr_support:
    141             flags |= h5f.ACC_SWMR_READ
--> 142         fid = h5f.open(name, flags, fapl=fapl)
    143     elif mode == 'r+':
    144         fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()
h5py/_objects.pyx in h5py._objects.with_phil.wrapper()
h5py/h5f.pyx in h5py.h5f.open()

OSError: Unable to open file (file signature not found)

> Detector Usage

detector = NudeDetector('./NudeNet-models/v1/detector_model')

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-9-de87406636d7> in <module>()
----> 1 detector = NudeDetector('./NudeNet-models/v1/detector_model')

5 frames
/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
    140         if swmr and swmr_support:
    141             flags |= h5f.ACC_SWMR_READ
--> 142         fid = h5f.open(name, flags, fapl=fapl)
    143     elif mode == 'r+':
    144         fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()
h5py/_objects.pyx in h5py._objects.with_phil.wrapper()
h5py/h5f.pyx in h5py.h5f.open()

OSError: Unable to open file (file signature not found)

## Specify versions of the following libraries
Environment : Colab
tf.__version__ : '1.14.0'
👇🏻👇🏻Check the link to see in Colab
[Run in Colab](https://colab.research.google.com/drive/1QNUREQ3xydXbit82uWEXQ6ZFORFwcHVa
)

## Expected behavior
Is there something wrong with the pre-trained model?
Hope to run it correctly
P.S: Wishing tflite version which was mentioned in README as ToDo release soon😃😃

## Screenshots
Just see Colab

**Comment by bedapudi6788** [comment]
NudeNet-models uses git-lfs and git clone will not work as expected. Please use wget to download the file(s).
