### ISSUE TITLE
Multiple warnings and errors pointing out to a CPU and model issue

### ISSUE THREAD

**Issue by ActivatingCounterMeasures** [bedapudi6788/NudeNet#19]
**Describe the bug and error messages (if any)**
I have many warnings concerning tensorflow, numpy and CPU related things.
You can see the output in the file below:
[errorOutput.txt](https://github.com/bedapudi6788/NudeNet/files/3579965/errorOutput.txt)

**The code snippet which gave this error**

`from nudenet import NudeDetector
detector = NudeDetector('Models/detector_model')
detector.detect('path_to_image')`

path_to_image is correctly filled in the real code snippet.

**Specify versions of the following libraries**
1. nudenet - latest
2. tensorflow/ tensorflow-gpu - 1.14.0
3. keras - 2.2.4

**Expected behavior**
Weirdly enough, I struggle to simply use a test code... It just have a simple output.

Any leads to resolve this issue please?

**Comment by bedapudi6788** [comment]
@ActivatingCounterMeasures i don't see any error in the output you attached. What is the actual error you are getting?

**Comment by ActivatingCounterMeasures** [comment]
@bedapudi6788 Well, you're right, there's no real error. But that's all the output I have. Where's the result of the code snippet? There must be a problem somewhere if I have this output?

**Comment by bedapudi6788** [comment]
@ActivatingCounterMeasures 

> Where's the result of the code snippet?

How do I know where the output is? Are you printing it somewhere? Are you saving it somewhere?

> There must be a problem somewhere if I have this output?

What output? Where exactly are you printing/saving the output from detector. Are you running the snippet in a interactive python terminal or are you running it as a file? At least try to provide some basic information.

**Comment by ActivatingCounterMeasures** [comment]
Welp... Sorry for wasting your time mate. Stupid mistake on my end, I thought `detector.detect('path_to_image')` would print the result on its own, but I had to put into a print. 
'Problem' solved.
