### ISSUE TITLE
Email

### ISSUE THREAD

**Issue by Kadantte** [bedapudi6788/NudeNet#2]
Hi, Please check your E-mail I emailed you with some more information, I hope you will credits [CTI](http://www.cti-community.net) they're the one who helps in collecting and labeling Data. and you can find their API here: [Pufiry](http://pury.fi) Discord: [CTI-Guild](https://discord.gg/k4qM4Jh).

**Comment by bedapudi6788** [comment]
Hey man, I thought you were the guy that collected this, that's why added credit to you. Of-course i will add it and also link to their site.

**Comment by bedapudi6788** [comment]
added it in bold in the readme. please lemme know if i missed any other info.
