### ISSUE TITLE
warnings and no result with Python 3.7 windows 64

### ISSUE THREAD

**Issue by aperveyev** [bedapudi6788/NudeNet#28]
pip install nudenet - OK
auto download classifier - OK

from nudenet import NudeClassifier
import sys
classifier = NudeClassifier()
classifier.classify(sys.argv[1])

python nude.py file.jpg

Nothing but warnings in stdout/stderr

> WARNING:tensorflow:From C:\Programs\Python37\lib\site-packages\keras\backend\tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.
> WARNING:tensorflow:From C:\Programs\Python37\lib\site-packages\keras\backend\tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.
> WARNING:tensorflow:From C:\Programs\Python37\lib\site-packages\keras\backend\tensorflow_backend.py:245: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.
> WARNING:tensorflow:From C:\Programs\Python37\lib\site-packages\keras\backend\tensorflow_backend.py:174: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.
> WARNING:tensorflow:From C:\Programs\Python37\lib\site-packages\keras\backend\tensorflow_backend.py:181: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.
> 2020-01-08 07:14:47.854098: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
> WARNING:tensorflow:From C:\Programs\Python37\lib\site-packages\keras\backend\tensorflow_backend.py:1834: The name tf.nn.fused_batch_norm is deprecated. Please use tf.compat.v1.nn.fused_batch_norm instead.
> WARNING:tensorflow:From C:\Programs\Python37\lib\site-packages\keras\backend\tensorflow_backend.py:3976: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.
> WARNING:tensorflow:From C:\Programs\Python37\lib\site-packages\keras\optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.
> WARNING:tensorflow:From C:\Programs\Python37\lib\site-packages\tensorflow\python\ops\math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use tf.where in 2.0, which has the same broadcast rule as np.where
> 

nudenet 1.1.0
tensorflow/ tensorflow-gpu 1.14.0 no GPU
keras 2.2.4

**Comment by bedapudi6788** [comment]
change "classifier.classify(sys.argv[1])" this line to "print(classifier.classify(sys.argv[1]))"
