### ISSUE TITLE
Train our Model

### ISSUE THREAD

**Issue by Kurumi-chan** [bedapudi6788/NudeNet#3]
Hello i saw your project in Reddit so i came here to ask by any chance you're going to share with us how you train your Model to train ours with our data-set? I hope if you're going to share with us the method it will be a big help to the community!

**Comment by bedapudi6788** [comment]
@Kurumi-chan , I am sorry, I didin't completely get you. Are you looking for the training scripts?

**Comment by Kurumi-chan** [comment]
@bedapudi6788 Yup the training script.

**Comment by jisheng047** [comment]
@bedapudi6788  Your working is amazing. But for my test dataset, which have a lot of baby images. The result is not good. I think you should add baby image to your negative samples.

**Comment by bedapudi6788** [comment]
@Kurumi-chan of course, I can share the scripts with you. Only thing is, they are not as well formatted or neatly written as the prediction parts. Shoot me an email at praneethbedapudi@gmail.com and I will share them with you.

**Comment by bedapudi6788** [comment]
@jisheng047 thank you. Good catch regarding the baby images, I concentrated on getting human sfw images but didn't consider the baby part. I will try to collect them too and add them in v2

**Comment by Kadantte** [comment]
@bedapudi6788 Thank's i Email you just now, gonna Close the issue for now.

**Comment by Kurumi-chan** [comment]
@bedapudi6788 Thank's i email you just now anyway going to close this issue until i want to ask something else if that is okay with you ofc.

**Comment by Kurumi-chan** [comment]
@bedapudi6788 Sorry about this, but i emailed you and didn't reply to my email, i hope if you have time you'll email me back.

**Comment by jisheng047** [comment]
@bedapudi6788  Have you updated the version 2 of this model? . Maybe i will help you crawl data for baby's dataset

**Comment by jisheng047** [comment]
@bedapudi6788 Which object detection's method did you use for detector nudity content?

**Comment by bedapudi6788** [comment]
@Kurumi-chan I emailed you the steps for training the object detection model.

**Comment by bedapudi6788** [comment]
@jisheng047 Right now I am kind of swamped at work :( . I will add add some baby images and re-train as soon as I get some time.

> Which object detection's method did you use for detector nudity content?

I used retinanet for object detection. The reason for using is explained in the blog post.

**Comment by jisheng047** [comment]
@bedapudi6788  thanks you

**Comment by jisheng047** [comment]
@bedapudi6788 Can you share me training script

**Comment by LinArcX** [comment]
Hi. And thank you you for for this great effort. Can you share the training script with us?

**Comment by Babar-Bashir** [comment]
@bedapudi6788  Can you please share the training script @ babar.bashir92@yahoo.com
Thanks

**Comment by bedapudi6788** [comment]
The training dataset (classification) is available at https://archive.org/details/NudeNet_classifier_dataset_v1

**Comment by harpavatkeerti** [comment]
@bedapudi6788 This is really an amazing work. I wanted to know more about the model details, and any training scripts you have. I want to train this model on another dataset. So it would be a big help if you could provide these. For reference, my mail id is harpavatkeerti@gmail.com. Thanks in advance

**Comment by jiseokkwak** [comment]
Hi can we have your training script @ jskwak@kaist.ac.kr
Thank you
