### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by abhishek9** [bedapudi6788/NudeNet#32]
**Describe the bug and error messages (if any)**
While trying to install in windows environment running python 3.8.2, I am getting error

**The code snippet which gave this error***
pip install nudenet

**Specify versions of the following libraries**
1. nudenet - from pip
2. tensorflow/ tensorflow-gpu - 2.2.0rc1
3. keras - 2.3.1

**Screenshots**
![error1](https://user-images.githubusercontent.com/1811958/77791075-00d65400-708c-11ea-80da-8bd614f40b68.png)

**Comment by bedapudi6788** [comment]
Try with python 3.6. I have not tested with 3.8.2.

**Comment by bedapudi6788** [comment]
Closing the issue for now. Feel free to re-open if you encounter any errors.
