### ISSUE TITLE
How to use pre-trained models directly?

### ISSUE THREAD

**Issue by oguzhancelikarslan** [bedapudi6788/NudeNet#33]
when trying to use "the client module" I end up encountering an error. I just want to use pre-trained models directly. Can you share an example with us?

**Comment by bedapudi6788** [comment]
If you are getting errors while installing client modules, I don't think you will be able to use the models directly.

Anyway, the clients themselves are the "examples" on how to use the modules.

**Comment by bedapudi6788** [comment]
I am closing the issue. Feel free to re-open if you need to.
