### ISSUE TITLE
Is it possible to train the nudeclassifier model on additional examples? 

### ISSUE THREAD

**Issue by aayushbhaskar** [bedapudi6788/NudeNet#35]
I want to train the model on some additional images which contain subtle nudity. Also, the nudedetector model starts employing about 24 cores of the server after testing on a few images which causes a heavy load on the server. Is there a workaround for this problem.

**Comment by bedapudi6788** [comment]
> I want to train the model on some additional images which contain subtle nudity.

Search for "finetune image classification model keras", and you will find a number of tutorials.

> Also, the nudedetector model starts employing about 24 cores of the server after testing on a few images which causes a heavy load on the server. 

It is impossible to debug without relevant information.

**Comment by bedapudi6788** [comment]
@aayushbhaskar closing the issue for now. Feel free to re-open if needed.
