### ISSUE TITLE
Detector dataset

### ISSUE THREAD

**Issue by superkido511** [bedapudi6788/NudeNet#41]
Hello!
Do you still have the dataset used to train the detector? I'm trying to build a nsfw detector with some different classes. It would be nice if you can share your dataset

**Comment by bedapudi6788** [comment]
https://github.com/notAI-tech/NudeNet/releases/download/v0/DETECTOR_AUTO_GENERATED_DATA.zip

**Comment by bedapudi6788** [comment]
Note that this is not manually labelled data (I don't have the rights to share the original manually labelled data).
