### ISSUE TITLE
No training configuration found in save file: the model was *not* compiled. Compile it manually.

### ISSUE THREAD

**Issue by negonix** [bedapudi6788/NudeNet#44]
**Describe the bug and error messages (if any)**

/home/negonix/anaconda3/envs/nude-net-github/lib/python3.6/site-packages/keras/engine/saving.py:292: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '

**Specify versions of the following libraries**
1. nudenet = 2.0.1
2. tensorflow/ tensorflow-gpu 1.14
3. keras 2.2.4

**This happened with this code:**

from nudenet import NudeDetector
detector = NudeDetector()

**Comment by negonix** [comment]
For some reason, if I run python _from the shell_ (not run a python file) and import NudeDetector and then call NudeDetector('base') then it works. But if I run a python file with the same code, or if I do it in the shell but omit the 'base' argument, then it gives me the same issue.

**Comment by bedapudi6788** [comment]
@negonix this is just a keras warning for inference checkpoint. This is expected and the detector will work fine after that.

**Comment by negonix** [comment]
Hello friend, the problem is that it does not work after this. The next
line in the code did not get executed, and it was
detector.detect(“sample.jpg”)

**Comment by bedapudi6788** [comment]
Can you copy paste the entire output, error and warning messages you got.

**Comment by negonix** [comment]
Hey I'm so sorry for the trouble, it turns out it works actually, I just forgot to print the output. I followed the example on the readme and I assumed that detector.detect() would automatically print for some reason. Rookie mistake man I'm sorry.

Thank you for this program and all your help!
