### ISSUE TITLE
"_run.sh: line 52:     6 Illegal instruction     (core dumped) python3 -u _loop.py" error on docker version of detector and classifier

### ISSUE THREAD

**Issue by MyAltGitHubAccount** [bedapudi6788/NudeNet#46]
**Describe the bug and error messages (if any)**
The docker container for the detector and classifier image never fully start. 

2020-08-15:00:56:25,236 INFO     [_utils.py:129] AVAILABLE FREE MEMORY: 78120.62890625; CACHE: 3906.0314453125 MB
2020-08-15:00:56:25,474 INFO     [_utils.py:129] AVAILABLE FREE MEMORY: 78120.625; CACHE: 3906.03125 MB
Using TensorFlow backend.
_run.sh: line 52:     6 Illegal instruction     (core dumped) python3 -u _loop.py
Waiting for prediction loop to begin.

System Specs:
ESXi VM, Ubuntu 18.04, 2x2.261GHz Intel Xeon L5640, 4GB RAM, GPU: svgadrmfb, Kernel: x86_64 Linux 5.4.0-42-generic

**The code snippet which gave this error***
docker run -it -p8081:8080 notaitech/nudenet:classifier

**Specify versions of the following libraries**
Latest docker image

**Expected behavior**
It should work? Never exits whatever loop generates "Waiting for prediction loop to begin".

**Comment by bedapudi6788** [comment]
Can you check if you are able to import nudenet inside the docker containe.
```bash
docker run -it -p8081:8080 notaitech/nudenet:classifier /bin/bash
python3
```
```python
from nudenet import NudeDetector
m = NudeDetector()
```

**Comment by MyAltGitHubAccount** [comment]
Sorry, just saw this. "Illegal instruction (core dumpted)", see below.

`
________                               _______________
___  __/__________________________________  ____/__  /________      __
__  /  _  _ \_  __ \_  ___/  __ \_  ___/_  /_   __  /_  __ \_ | /| / /
_  /   /  __/  / / /(__  )/ /_/ /  /   _  __/   _  / / /_/ /_ |/ |/ /
/_/    \___//_/ /_//____/ \____//_/    /_/      /_/  \____/____/|__/


WARNING: You are running this container as root, which can cause new files in
mounted volumes to be created as the root user on your host machine.

To avoid this, run the container by specifying your user's userid:

$ docker run -u $(id -u):$(id -g) args...

root@d1762dd52352:/app# python3
Python 3.6.8 (default, Jan 14 2019, 11:02:34)
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from nudenet import NudeDetector
Using TensorFlow backend.
Illegal instruction (core dumped)`

**Comment by TomasKopecky** [comment]
> Sorry, just saw this. "Illegal instruction (core dumpted)", see below.
> 
> `
> 
> ___ **/**________________________________ ****/** /**______ __
> __ / _ _ _ __ _ ___/ __ _ ___/_ /_ __ /_ __ _ | /| / / _ / / **/ / / /(** )/ /_/ / / _ __/ _ / / /_/ /_ |/ |/ /
> /_/ ___//_/ /_//__**/ _**_//_/ /_/ /_/ __**/**__/|__/
> 
> WARNING: You are running this container as root, which can cause new files in
> mounted volumes to be created as the root user on your host machine.
> 
> To avoid this, run the container by specifying your user's userid:
> 
> $ docker run -u $(id -u):$(id -g) args...
> 
> root@d1762dd52352:/app# python3
> Python 3.6.8 (default, Jan 14 2019, 11:02:34)
> [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > from nudenet import NudeDetector
> > > > Using TensorFlow backend.
> > > > Illegal instruction (core dumped)`

I have exactly the same problem.

**Comment by bedapudi6788** [comment]
@ronadlisko @MyAltGitHubAccount sorry for delayed response. I am am unable to reproduce this on my devices. If possible can you check if you are able to use tensorflow inside the containers.
```bash
docker run -it -p8081:8080 notaitech/nudenet:classifier /bin/bash
python3
```

```python
import tensorflow as tf

```

**Comment by TomasKopecky** [comment]
Unfortunately not, python returns "Illegal instruction" statement. When I check the pip list of installed modules, tensorflow 1.14.0 is normaly there.

**Comment by bedapudi6788** [comment]
Oh! NudeNet's docker image is built from `tensorflow/tensorflow:1.14.0-py3` I am not entirely sure why it is failing though. Are you running on Windows (even on windows it should work though!)?

**Comment by TomasKopecky** [comment]
Yes, I am running it in Docker on Windows 10.

**Comment by TomasKopecky** [comment]
Finally, Im am able to run the image properly in Docker by uninstalling the tensorflow 1.14 version and installing the 1.5 version. Now the classifier works fine.

**Comment by bedapudi6788** [comment]
@ronadlisko the latest images now use tensorflow 1.15.4 and no longer depend on keras-retinanet and keras libraries. You might be able to run this.

**Comment by TomasKopecky** [comment]
@bedapudi6788 My problem was that a computer I was running your network on didn't support neither AVX nor CUDA. Because of lots problems with building tensorflow from source and so on I am running it now on another computer with AVX and everything runs perfectly. Thanks anyway.
