### ISSUE TITLE
TypeError: data type not understood

### ISSUE THREAD

**Issue by foozzi** [bedapudi6788/NudeNet#49]
**Describe the bug and error messages (if any)**
https://pastebin.ubuntu.com/p/FYmNPbhrC5/

**The code snippet which gave this error**
```python
from nudenet import NudeDetector


detector = NudeDetector()
print(detector.detect('./88676111_215_ed12.jpg'))
```
**Specify versions of the following libraries**

1. nudenet 2.0.3
2. tensorflow/ tensorflow-gpu 2.3.0
3. keras 2.4.3

**Expected behavior**
detecting nude image or video

**Comment by foozzi** [comment]
Describe the bug and error messages (if any)
https://pastebin.ubuntu.com/p/FYmNPbhrC5/

The code snippet which gave this error*

from nudenet import NudeDetector


detector = NudeDetector()
print(detector.detect('./88676111_215_ed12.jpg'))

Specify versions of the following libraries

    nudenet 2.0.3
    tensorflow/ tensorflow-gpu 2.3.0
    keras 2.4.3

Expected behavior
detecting nude image or video
Screenshots

**Comment by bedapudi6788** [comment]
I have not tested the detector with tf 2.3 and keras 2.4.3. `keras==2.2.4` and `tf==1.14` are the versions the repo is currently tested with.

**Comment by foozzi** [comment]
> I have not tested the detector with tf 2.3 and keras 2.4.3. `keras==2.2.4` and `tf==1.14` are the versions the repo is currently tested with.

ok dude, i'm try this!

**Comment by foozzi** [comment]
> I have not tested the detector with tf 2.3 and keras 2.4.3. `keras==2.2.4` and `tf==1.14` are the versions the repo is currently tested with.

hm, how to i can install tf 1.14 on python 3.8.3 linux?

**Comment by bedapudi6788** [comment]
Installing miniconda (https://docs.conda.io/en/latest/miniconda.html) and creating a environment with lower python version (`conda create -n py36 python=3.6`) is an option.

**Comment by foozzi** [comment]
> Installing miniconda (https://docs.conda.io/en/latest/miniconda.html) and creating a environment with lower python version (`conda create -n py36 python=3.6`) is an option.

thx, I spent 3-4 hours building cuda and tensorflow 1.14 and got an error at the end xD

**Comment by bedapudi6788** [comment]
I am closing the issue for now. Feel free to re-open if needed.
