### ISSUE TITLE
keras-retinanet is deprecated

### ISSUE THREAD

**Issue by nn12343456** [bedapudi6788/NudeNet#50]
https://github.com/fizyr/keras-retinanet
See the warning

This might interfere with enabling new Tensorflow versions: loading the model fails with the TF 2.4 nightly build.

**Comment by bedapudi6788** [comment]
Thanks for letting me know. Please note that, at the moment I don't have plans to support further tf/keras versions. As the sole maintainer of this project, it is very hard to keep up with all the changes in different versions of tf and keras.

**Comment by nn12343456** [comment]
Understood.

For posterity: I got it working on the CPU with TF 2.3 using suggestions in other Github issues but I don't know if that would break your platform because I don't know what you platform is. I tried building for the 2.4 nightlies because I believe 2.4 will be the earliest version that supports CUDA on Nvidia 3000 series.

**Comment by bedapudi6788** [comment]
@nn12343456 I will remove the dependency on keras and keras-retinanet and support all tensorflow versions in the next release. Cannot guarantee the timeline though!

**Comment by bedapudi6788** [comment]
@nn12343456  from the current release, nudenet doesn't require any version of tensorflow and will work as expected on all newer python versions.
