### ISSUE TITLE
V2 detector dataset

### ISSUE THREAD

**Issue by karthickai** [bedapudi6788/NudeNet#53]
Thanks for your excellent work !!

Could you share us latest detector dataset.

**Comment by bedapudi6788** [comment]
> Thanks for your excellent work !!

thank you

> Could you share us latest detector dataset.

Unfortunately, I don't have the data (It was auto-generated on the fly and fed to fit_generator and I was too cheap to back it up). The few (~12,000) images I shared are the ones saved for evaluation.
