### ISSUE TITLE
Html report with classification and image display

### ISSUE THREAD

**Issue by uBadRequest** [bedapudi6788/NudeNet#57]
**Feature Request**
Generate an HTML document with the classifications, image, and the path/filename.

This would be awesome. :+1:

**Comment by bedapudi6788** [comment]
@uBadRequest can you give an example of what you mean? Are you looking for a html page where you can upload a file and get the result in that page?

**Comment by uBadRequest** [comment]
> @uBadRequest can you give an example of what you mean? Are you looking for a html page where you can upload a file and get the result in that page?

I'm perfectly fine with the command line, but a flag for output like `--output scan-1.html`

**Comment by bedapudi6788** [comment]
This is out of scope for this project. You are welcome to send a pull request with this feature though. I will test and merge it.
