### ISSUE TITLE
how to host it as a webapi

### ISSUE THREAD

**Issue by mnaveenswamy** [bedapudi6788/NudeNet#58]
hi,

Thanks for directing me to the github, I have certain questions 

how to host it as a webapi,
can I make call with http, 
will i need your data or dataset to predict,
also can I train it with more data,
where do i keep the trained data and datasets

Thanks and Regards,
naveen

**Comment by bedapudi6788** [comment]
https://github.com/notAI-tech/NudeNet#as-self-hostable-api-service this section has the docker command which starts the API.

https://github.com/notAI-tech/fastDeploy/blob/master/cli/fastDeploy-file_client.py shows how to send a image to the webapi via post request and get the predictions.

**Comment by mnaveenswamy** [comment]
many thanks for your reply, will try as suggested, how can I train it with more data, may be I need to loop with batch or individual,
where do i keep the trained result of data and datasets

thanks and regards

**Comment by bedapudi6788** [comment]
> how can I train it with more data,

Take a look at the keras-retinanet repo

> where do i keep the trained result of data and datasets

Same as above.
