### ISSUE TITLE
Can it be used with dart , flutter? 

### ISSUE THREAD

**Issue by JackTheProgrammer** [bedapudi6788/NudeNet#59]
I am a software guy and I had to make a project where people will share short short videos, and I have to make sure that no pornographic material is exchanged among users, if there's an alternative then please tell me.

**Comment by bedapudi6788** [comment]
From client side, I don't know (I have zero experience with dart/flutter or building apps for any mobile platofrms). From server side, sure.

**Comment by ibnux** [comment]
Nope, it cannot, because it will need many python library and others, that will not support in mobile phone
use it on server side

**Comment by JackTheProgrammer** [comment]
> Nope, it cannot, because it will need many python library and others, that will not support in mobile phone
> use it on server side

thanks

**Comment by ndaysinaiK** [comment]
I tried it with TensorFlow lite and flutter, It worked with a score of 85%.
amazing work 👍

**Comment by bedapudi6788** [comment]
@ndaysinaiK if possible can you post a script/functions showing how to do this. This will help people like @JackTheProgrammer who are looking to integrate this on-device.

**Comment by ndaysinaiK** [comment]
Hi @bedapudi6788,
I just uploaded a file and some instructions here :  https://github.com/ndaysinaiK/nude-test

**Comment by bedapudi6788** [comment]
@ndaysinaiK thank you for adding the example. I am linking your repository in the READMe.
