### ISSUE TITLE
Video detector, limit range video

### ISSUE THREAD

**Issue by ibnux** [bedapudi6788/NudeNet#60]
Can we limit range video to detect?

or until it found some classname i set, it will stop

i only need to detect if the video has EXPOSED_* with above score i set, it will stop to scan if found one

**Comment by bedapudi6788** [comment]
There is no option to do this directly at the moment. Although, it is fairly easy to do. https://github.com/notAI-tech/NudeNet/blob/6573d9ee5334d4666c59bbae9d3693f8b6fdf6b8/nudenet/detector.py#L103 You will have to add your if condition in this loop and break if it is met.

**Comment by ibnux** [comment]
i was read the source code think about to edit it from that 

Thank you 👍
