### ISSUE TITLE
Nudenet Training

### ISSUE THREAD

**Issue by ghost** [bedapudi6788/NudeNet#61]
Hello @bedapudi6788 . I am just learning how to teach and create artificial intelligence and I am afraid my problem will seem silly, but recently I came across your project Nudenet and I liked it. _I would like to know if there is any way to teach it more?_ It is already well trained, but in some points it is too categorical and I would like to teach it a little bit more or teach it new content, and if possible, could you help me with that?
Thank you in advance.

**Comment by bedapudi6788** [comment]
For training/fine-tuning, you need to look at https://github.com/fizyr/keras-retinanet. In general, you will need more data tagged in that format and can finetune from one of the provided checkpoints.

**Comment by ghost** [comment]
Thank you for your quick answer, you helped me.
