### ISSUE TITLE
core dumped error by running nudenet:detector docker image

### ISSUE THREAD

**Issue by ehsanm94** [bedapudi6788/NudeNet#66]
I got core dumped error by running `docker run -it -p8080:8080 notaitech/nudenet:detector`

The docker image is the most recently published image and I got the same error by importing nudenet or tensorflow inside the docker container.

System Specs:
CPU: Intel Xeon X5650

![Screenshot from 2020-11-25 20-48-17](https://user-images.githubusercontent.com/16461278/100261167-9b5e9e00-2f5f-11eb-9782-459c8bd1b35f.png)

**Comment by bedapudi6788** [comment]
https://github.com/notAI-tech/NudeNet/issues/46#issuecomment-711419370

I believe this is the same issue.

**Comment by ehsanm94** [comment]
Exactly! My CPU's instruction sets does not include AVX instructions.

It seems the easiest solution for me is using anaconda and install tensorflow by it. [link](https://github.com/tensorflow/tensorflow/issues/24548#issuecomment-605016573)

**Comment by bedapudi6788** [comment]
@ehsanm94 I am closing this issue. Feel free to re-open if required.
