### ISSUE TITLE
Can you release the ground truth for NSFW/SFW classification dataset? 

### ISSUE THREAD

**Issue by neoyang0620** [bedapudi6788/NudeNet#68]
Hi,
Thanks for your amazing work. I downloaded NudeNet_classifier_dataset_v1. You split the dataset into train/val/test sets. However, in each set, there are three sub-folders: sexy, nude, and safe. My question is, what the ground-truth labels for images in the "sexy" folder? 

Best,
Neo

**Comment by bedapudi6788** [comment]
in the released model, sexy + nude is unsafe and safe is safe. When scraping the data I tried to collect it in the above 3 categories, but later changed it to 2.
