### ISSUE TITLE
onnxruntime gpu support

### ISSUE THREAD

**Issue by shady145** [bedapudi6788/NudeNet#71]
Will we be able to use the GPU now that nudenet uses onnxruntime ?

**Comment by bedapudi6788** [comment]
Yes. you can just uninstall onnxruntime and install onnxruntime-gpu if you want to use gpu.

**Comment by shady145** [comment]
When using onnxruntime-gpu im getting ModuleNotFoundError: No module named 'onnxruntime'.
Can't find anything about it online.
Any clue ?

**Comment by bedapudi6788** [comment]
Can you reproduce the issue in a colab notebook and post it here?
