### ISSUE TITLE
How to use this for someone with no programing experience.

### ISSUE THREAD

**Issue by till161** [bedapudi6788/NudeNet#74]
Hello, I have been attempting to figure out how to run this for a while now and so far have been unsuccessful in my attempts.
So I was hoping that some kind person here would be able to write a little tutorial on how to use this program for someone who has no experience in programing.

Thanks

**Comment by bedapudi6788** [comment]
@till161 do you want to run this on a Windows machine or Mac? 

Also, can you explain your use case a little bit. i.e: what do you plan on using NudeNet for (for eg, you have N images in a folder. You want to separate safe and unsafe etc.).

**Comment by till161** [comment]
Sorry forgot stuff like that would be important, I'm using Windows 10.

I would like to be able to use the Classifier to separate safe and unsafe image into separate folders, and then Detector to categorize these images into their own folder.

**Comment by bedapudi6788** [comment]
@till161 https://github.com/notAI-tech/NudeNet/issues/75#issuecomment-773025747 please take a look at this comment.
