### ISSUE TITLE
I am dumb.

### ISSUE THREAD

**Issue by Pokester7** [bedapudi6788/NudeNet#75]
Even though i read through your webite of how to installa nd use nudenet Im still confsued on how to download and use it and was wondering if you do a video tutorial on it

regards, poke

**Comment by bedapudi6788** [comment]
@Pokester7 Open https://colab.research.google.com/drive/1GKa5Y11vJdK4nn7Hhp2H0NALJnBl1Jhg?usp=sharing

Steps to use this.

<img width="339" alt="Screenshot 2021-02-04 at 10 15 59 AM" src="https://user-images.githubusercontent.com/15898654/106845958-fcc68a00-66d1-11eb-99bd-e9538fac7441.png">

Upload your images by clicking on the folder icon and the upload button (shown in above screenshot)


<img width="345" alt="Screenshot 2021-02-04 at 10 17 23 AM" src="https://user-images.githubusercontent.com/15898654/106846071-2da6bf00-66d2-11eb-9864-1c3e4ae1bf31.png">

In each cell, hover over the left top corner and there will be a "play" button (shown in above screenshot). Click it and move on to the next cell.


<img width="990" alt="Screenshot 2021-02-04 at 10 18 15 AM" src="https://user-images.githubusercontent.com/15898654/106846134-4ca55100-66d2-11eb-9662-cb393ffbb796.png">


It will print the predictions for all the images you uploaded.
