### ISSUE TITLE
classifier output order

### ISSUE THREAD

**Issue by AbdallaHefny** [bedapudi6788/NudeNet#76]
The classifier's default categories are [unsafe, safe]. 
But in the readme you reversed the order: 
```
classifier.classify('path_to_image_1')
# Returns {'path_to_image_1': {'safe': PROBABILITY, 'unsafe': PROBABILITY}}
```

This may be so misleading if not clear.

**Comment by bedapudi6788** [comment]
how does that matter? it is a dict. not a list or tuple where order matters.

**Comment by AbdallaHefny** [comment]
The order is reversed: safe goes to unsafe

**Comment by AbdallaHefny** [comment]
you are right, I thought you were mapping first output(unsafe) to first dictionary key. But I checked the code again, it is dynamic. 
Thanks for the clarification.
